import { useQuery } from "@tanstack/react-query";
import { useState } from "react";

interface WrappedData {
  period: string;
  sessions: number;
  messages: number;
  toolCalls: number;
  filesChanged: number;
  totalCost: number;
  topModel: { name: string; sessions: number; cost: number };
  topProject: { name: string; sessions: number; cost: number };
  topTool: { name: string; count: number };
  mostExpensiveSession: { id: string; cost: number; project: string; messages: number };
  mostProductiveSession: { id: string; filesChanged: number; cost: number; project: string };
  dailyPattern: Array<{ day: string; sessions: number }>;
  funFacts: string[];
}

export function Wrapped(): React.ReactElement {
  const [type, setType] = useState<"weekly" | "monthly">("weekly");
  const { data, isLoading } = useQuery({
    queryKey: ["wrapped", type],
    queryFn: () => fetch(`/api/analytics/wrapped?type=${type}`).then((r) => r.json() as Promise<WrappedData>),
  });

  if (isLoading || !data) return <div className="p-6 text-zinc-500">Loading...</div>;

  const maxSessions = Math.max(...(data.dailyPattern.map((d) => d.sessions) || [1]));

  return (
    <div className="p-6 flex flex-col items-center">
      <div className="flex gap-2 mb-6">
        <button onClick={() => setType("weekly")} className={`px-3 py-1 rounded-lg text-xs ${type === "weekly" ? "bg-blue-500 text-white" : "bg-zinc-800 text-zinc-400"}`}>Weekly</button>
        <button onClick={() => setType("monthly")} className={`px-3 py-1 rounded-lg text-xs ${type === "monthly" ? "bg-blue-500 text-white" : "bg-zinc-800 text-zinc-400"}`}>Monthly</button>
      </div>

      {/* The Shareable Card */}
      <div id="wrapped-card" className="w-full max-w-lg rounded-2xl border border-zinc-700 bg-gradient-to-br from-zinc-900 via-zinc-950 to-zinc-900 p-8 shadow-2xl">
        <div className="text-center mb-6">
          <p className="text-xs text-zinc-500 uppercase tracking-widest">Rasad AI Wrapped</p>
          <h1 className="text-2xl font-bold text-white mt-1">{data.period}</h1>
        </div>

        {/* Big stats */}
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="text-center">
            <p className="text-3xl font-bold text-blue-400 font-mono">{data.sessions}</p>
            <p className="text-[10px] text-zinc-500 uppercase">Sessions</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-cyan-400 font-mono">{data.messages.toLocaleString()}</p>
            <p className="text-[10px] text-zinc-500 uppercase">Messages</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-yellow-400 font-mono">${data.totalCost.toFixed(0)}</p>
            <p className="text-[10px] text-zinc-500 uppercase">Spent</p>
          </div>
        </div>

        <div className="h-px bg-zinc-800 mb-6" />

        {/* Highlights */}
        <div className="space-y-3 mb-6">
          <Row label="Favorite Model" value={data.topModel.name.replace("claude-", "").split("/").pop() ?? ""} sub={`${data.topModel.sessions} sessions`} />
          <Row label="Top Project" value={data.topProject.name.split("/").pop() ?? ""} sub={`${data.topProject.sessions} sessions`} />
          <Row label="Top Tool" value={data.topTool.name} sub={`${data.topTool.count} calls`} />
          <Row label="Files Changed" value={String(data.filesChanged)} sub={`${data.toolCalls.toLocaleString()} tool calls`} />
        </div>

        <div className="h-px bg-zinc-800 mb-6" />

        {/* Daily pattern */}
        <div className="mb-6">
          <p className="text-[10px] text-zinc-500 uppercase mb-3">Activity by Day</p>
          <div className="space-y-1">
            {data.dailyPattern.map((d) => (
              <div key={d.day} className="flex items-center gap-2">
                <span className="text-[10px] text-zinc-500 w-7">{d.day}</span>
                <div className="flex-1 h-3 bg-zinc-800 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-500/70 rounded-full" style={{ width: `${(d.sessions / maxSessions) * 100}%` }} />
                </div>
                <span className="text-[10px] text-zinc-600 w-6 text-right">{d.sessions}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Fun facts */}
        {data.funFacts.length > 0 && (
          <>
            <div className="h-px bg-zinc-800 mb-4" />
            <div className="space-y-1.5">
              {data.funFacts.slice(0, 3).map((fact, i) => (
                <p key={i} className="text-[11px] text-zinc-400 leading-relaxed">{fact}</p>
              ))}
            </div>
          </>
        )}

        <div className="h-px bg-zinc-800 mt-6 mb-4" />
        <p className="text-[9px] text-zinc-700 text-center">Generated by Rasad — AI Observatory</p>
      </div>

      <p className="text-xs text-zinc-600 mt-4">Screenshot this card and share on X / LinkedIn</p>
    </div>
  );
}

function Row({ label, value, sub }: { label: string; value: string; sub: string }): React.ReactElement {
  return (
    <div className="flex items-center justify-between">
      <span className="text-xs text-zinc-500">{label}</span>
      <div className="text-right">
        <span className="text-sm text-white font-medium">{value}</span>
        <span className="text-[10px] text-zinc-600 ml-2">{sub}</span>
      </div>
    </div>
  );
}
