import { useQuery } from "@tanstack/react-query";
import { useState, useCallback } from "react";
import { Loading } from "../components/Loading";

interface WrappedData {
  period: string;
  sessions: number;
  messages: number;
  toolCalls: number;
  filesChanged: number;
  totalCost: number;
  topModel: { name: string; sessions: number; cost: number };
  topProject: { name: string; sessions: number; cost: number };
  topTool: { name: string; count: number };
  mostExpensiveSession: { id: string; cost: number; project: string; messages: number };
  mostProductiveSession: { id: string; filesChanged: number; cost: number; project: string };
  dailyPattern: Array<{ day: string; sessions: number }>;
  funFacts: string[];
}

export function Wrapped(): React.ReactElement {
  const [type, setType] = useState<"weekly" | "monthly">("weekly");
  const [copied, setCopied] = useState(false);
  const { data, isLoading } = useQuery({
    queryKey: ["wrapped", type],
    queryFn: () => fetch(`/api/analytics/wrapped?type=${type}`).then((r) => r.json() as Promise<WrappedData>),
  });

  const handleCopy = useCallback(() => {
    if (!data) return;
    const text = [
      `AI Wrapped - ${data.period}`,
      `${data.sessions} sessions | ${data.messages.toLocaleString()} messages | $${data.totalCost.toFixed(0)} spent`,
      `Top model: ${data.topModel.name.split("/").pop()?.replace("claude-", "")}`,
      `Top project: ${data.topProject.name.split("/").pop()}`,
      `Top tool: ${data.topTool.name} (${data.topTool.count} calls)`,
      "",
      "Generated by Rasad - AI Observatory",
    ].join("\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [data]);

  if (isLoading || !data) return <Loading message="Generating your wrapped..." />;

  const maxSessions = Math.max(...(data.dailyPattern.map((d) => d.sessions) || [1]));

  return (
    <div className="p-6 flex flex-col items-center">
      {/* Type toggle */}
      <div className="flex gap-2 mb-6">
        <button
          onClick={() => setType("weekly")}
          className={`px-4 py-1.5 rounded-lg text-xs font-medium transition-all ${
            type === "weekly"
              ? "bg-blue-500 text-white shadow-lg shadow-blue-500/20"
              : "bg-zinc-800 text-zinc-400 hover:text-white"
          }`}
        >
          This Week
        </button>
        <button
          onClick={() => setType("monthly")}
          className={`px-4 py-1.5 rounded-lg text-xs font-medium transition-all ${
            type === "monthly"
              ? "bg-blue-500 text-white shadow-lg shadow-blue-500/20"
              : "bg-zinc-800 text-zinc-400 hover:text-white"
          }`}
        >
          This Month
        </button>
      </div>

      {/* The Shareable Card */}
      <div className="w-full max-w-lg rounded-2xl bg-gradient-to-br from-blue-500/10 via-transparent to-purple-500/10 p-px">
        <div id="wrapped-card" className="rounded-2xl bg-gradient-to-br from-zinc-900 via-zinc-950 to-zinc-900 p-8">
          {/* Header */}
          <div className="text-center mb-8">
            <p className="text-[10px] text-zinc-500 uppercase tracking-[0.2em] font-medium">Rasad AI Wrapped</p>
            <h1 className="text-2xl font-bold text-white mt-2">{data.period}</h1>
          </div>

          {/* Big stats row */}
          <div className="grid grid-cols-3 gap-4 mb-8">
            <BigStat value={String(data.sessions)} label="Sessions" color="text-blue-400" />
            <BigStat value={data.messages.toLocaleString()} label="Messages" color="text-cyan-400" />
            <BigStat value={`$${data.totalCost.toFixed(0)}`} label="Spent" color="text-yellow-400" />
          </div>

          <div className="h-px bg-gradient-to-r from-transparent via-zinc-700 to-transparent mb-6" />

          {/* Highlights */}
          <div className="space-y-3 mb-6">
            <Row label="Favorite Model" value={data.topModel.name.replace("claude-", "").split("/").pop() ?? ""} sub={`${data.topModel.sessions} sessions | $${data.topModel.cost.toFixed(0)}`} />
            <Row label="Top Project" value={data.topProject.name.split("/").pop() ?? ""} sub={`${data.topProject.sessions} sessions | $${data.topProject.cost.toFixed(0)}`} />
            <Row label="Top Tool" value={data.topTool.name} sub={`${data.topTool.count.toLocaleString()} calls`} />
            <Row label="Files Changed" value={String(data.filesChanged)} sub={`${data.toolCalls.toLocaleString()} tool calls total`} />
          </div>

          <div className="h-px bg-gradient-to-r from-transparent via-zinc-700 to-transparent mb-6" />

          {/* Activity heatmap */}
          <div className="mb-6">
            <p className="text-[10px] text-zinc-500 uppercase tracking-wider mb-3">Activity by Day</p>
            <div className="space-y-1.5">
              {data.dailyPattern.map((d) => (
                <div key={d.day} className="flex items-center gap-2">
                  <span className="text-[10px] text-zinc-500 w-8 font-medium">{d.day}</span>
                  <div className="flex-1 h-4 bg-zinc-800/50 rounded-md overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-blue-500/60 to-blue-400/40 rounded-md transition-all"
                      style={{ width: `${(d.sessions / maxSessions) * 100}%` }}
                    />
                  </div>
                  <span className="text-[10px] text-zinc-600 w-6 text-right font-mono">{d.sessions}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Fun facts */}
          {data.funFacts.length > 0 && (
            <>
              <div className="h-px bg-gradient-to-r from-transparent via-zinc-700 to-transparent mb-4" />
              <div className="space-y-2">
                {data.funFacts.slice(0, 3).map((fact, i) => (
                  <p key={i} className="text-[11px] text-zinc-400 leading-relaxed pl-3 border-l border-zinc-700">{fact}</p>
                ))}
              </div>
            </>
          )}

          <div className="h-px bg-gradient-to-r from-transparent via-zinc-700 to-transparent mt-6 mb-4" />
          <p className="text-[9px] text-zinc-700 text-center tracking-wider">Generated by Rasad &mdash; AI Observatory</p>
        </div>
      </div>

      {/* Share actions */}
      <div className="flex items-center gap-3 mt-5">
        <button
          onClick={handleCopy}
          className={`px-4 py-2 rounded-lg text-xs font-medium transition-all ${
            copied
              ? "bg-green-500/20 text-green-400 border border-green-500/30"
              : "bg-zinc-800 text-zinc-400 hover:text-white border border-zinc-700 hover:border-zinc-600"
          }`}
        >
          {copied ? "Copied!" : "Copy as Text"}
        </button>
        <p className="text-xs text-zinc-600">Screenshot the card to share on X / LinkedIn</p>
      </div>
    </div>
  );
}

function BigStat({ value, label, color }: { value: string; label: string; color: string }): React.ReactElement {
  return (
    <div className="text-center">
      <p className={`text-3xl font-bold font-mono ${color}`}>{value}</p>
      <p className="text-[10px] text-zinc-500 uppercase tracking-wider mt-1">{label}</p>
    </div>
  );
}

function Row({ label, value, sub }: { label: string; value: string; sub: string }): React.ReactElement {
  return (
    <div className="flex items-center justify-between">
      <span className="text-xs text-zinc-500">{label}</span>
      <div className="text-right">
        <span className="text-sm text-white font-medium">{value}</span>
        <span className="text-[10px] text-zinc-600 ml-2">{sub}</span>
      </div>
    </div>
  );
}
