import type Database from "better-sqlite3";
import { generatePassport } from "./session-passport.js";
import { generateVibeDiff } from "./vibe-diff.js";

export function exportPassportMarkdown(db: Database.Database, sessionId: string): string | null {
  const passport = generatePassport(db, sessionId);
  if (!passport) return null;

  const lines: string[] = [];
  const projectName = passport.project.split("/").pop() ?? passport.project;

  lines.push(`# Session Passport`);
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Project** | ${projectName} |`);
  lines.push(`| **Model** | ${passport.model ?? "—"} |`);
  lines.push(`| **Date** | ${passport.date} |`);
  lines.push(`| **Duration** | ${passport.duration} |`);
  lines.push(`| **Cost** | $${passport.cost.total.toFixed(2)} |`);
  lines.push(`| **Messages** | ${passport.summary.messageCount} (${passport.summary.userMessages} user, ${passport.summary.assistantMessages} AI) |`);
  lines.push(`| **Tool Calls** | ${passport.summary.toolCallCount} |`);
  lines.push(`| **Files** | ${passport.summary.uniqueFilesCount} |`);
  lines.push("");

  if (passport.toolsUsed.length > 0) {
    lines.push("## Tools Used");
    lines.push("");
    lines.push("| Tool | Count | % |");
    lines.push("|---|---|---|");
    for (const t of passport.toolsUsed) {
      lines.push(`| ${t.tool} | ${t.count} | ${t.percentage}% |`);
    }
    lines.push("");
  }

  if (passport.filesTouched.length > 0) {
    lines.push("## Files Touched");
    lines.push("");
    for (const f of passport.filesTouched) {
      const actions = f.actions.join("/");
      lines.push(`- \`${f.path}\` (${actions}, ${f.count}x)`);
    }
    lines.push("");
  }

  if (passport.decisions.length > 0) {
    lines.push("## User Decisions");
    lines.push("");
    for (const d of passport.decisions) {
      lines.push(`> ${d.slice(0, 200)}`);
      lines.push("");
    }
  }

  if (passport.keyMoments.length > 0) {
    lines.push("## Key Moments");
    lines.push("");
    for (const m of passport.keyMoments) {
      lines.push(`- ${m.description}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by [Rasad](https://github.com/shami-ah/rasad) — AI Observatory*`);

  return lines.join("\n");
}

export function exportVibeDiffMarkdown(db: Database.Database, sessionId: string): string | null {
  const diff = generateVibeDiff(db, sessionId);
  if (!diff) return null;

  const lines: string[] = [];
  const projectName = diff.project.split("/").pop() ?? diff.project;

  lines.push(`# Vibe Diff`);
  lines.push("");
  lines.push(`**${projectName}** — ${diff.date} — ${diff.duration}`);
  lines.push("");

  lines.push("## Overview");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Turns | ${diff.overview.totalTurns} |`);
  lines.push(`| User prompts | ${diff.overview.userPrompts} |`);
  lines.push(`| AI responses | ${diff.overview.aiResponses} |`);
  lines.push(`| Tool calls | ${diff.overview.toolCalls} |`);
  lines.push(`| Files created | ${diff.overview.filesCreated} |`);
  lines.push(`| Files edited | ${diff.overview.filesEdited} |`);
  lines.push(`| Files read | ${diff.overview.filesRead} |`);
  lines.push(`| Cost | $${diff.overview.estimatedCost.toFixed(2)} |`);
  lines.push("");

  if (diff.filesChanged.filter((f) => f.action !== "read").length > 0) {
    lines.push("## Files Changed");
    lines.push("");
    for (const f of diff.filesChanged.filter((f) => f.action !== "read")) {
      const icon = f.action === "write" ? "+" : "~";
      lines.push(`- ${icon} \`${f.path}\` (${f.occurrences}x)`);
    }
    lines.push("");
  }

  if (diff.retries.length > 0) {
    lines.push("## Retries");
    lines.push("");
    for (const r of diff.retries) {
      lines.push(`- ${r.description}`);
    }
    lines.push("");
  }

  if (diff.toolBreakdown.length > 0) {
    lines.push("## Tool Breakdown");
    lines.push("");
    lines.push("| Tool | Count | % |");
    lines.push("|---|---|---|");
    for (const t of diff.toolBreakdown) {
      lines.push(`| ${t.tool} | ${t.count} | ${t.percentage}% |`);
    }
    lines.push("");
  }

  lines.push("## Conversation");
  lines.push("");
  for (const turn of diff.conversation) {
    if (turn.role === "user") {
      lines.push(`**User:** ${turn.preview.slice(0, 200)}`);
    } else {
      const tools = turn.toolCalls.length > 0 ? ` [${turn.toolCalls.join(", ")}]` : "";
      lines.push(`**AI:** ${turn.preview.slice(0, 150)}${tools}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by [Rasad](https://github.com/shami-ah/rasad) — AI Observatory*`);

  return lines.join("\n");
}
