import chalk from "chalk";
import ora from "ora";
import { writeFileSync } from "node:fs";
import { getDb, closeDb } from "../../db/connection.js";
import { generateAISummary } from "../../analysis/ai-summary.js";

export async function runSummarize(
  sessionId: string,
  opts: { apiKey?: string; json?: boolean; md?: boolean }
): Promise<void> {
  const db = getDb();
  try {
    const resolved = db.prepare("SELECT id FROM sessions WHERE id LIKE ? LIMIT 1").get(`${sessionId}%`) as { id: string } | undefined;
    if (!resolved) {
      console.log(chalk.red(`Session not found: ${sessionId}`));
      return;
    }

    const spinner = ora("Generating AI summary...").start();

    try {
      const summary = await generateAISummary(db, resolved.id, opts.apiKey);
      spinner.stop();

      if (opts.json) {
        console.log(JSON.stringify(summary, null, 2));
        return;
      }

      if (opts.md) {
        const md = formatMarkdown(summary);
        const filename = `summary-${sessionId.slice(0, 8)}.md`;
        writeFileSync(filename, md);
        console.log(chalk.green(`\n  Exported to ${filename}\n`));
        return;
      }

      // Terminal output
      console.log("");
      console.log(chalk.bold("  AI Session Summary"));
      console.log(chalk.dim(`  ${resolved.id} — via ${summary.provider}/${summary.model}`));
      console.log("");
      console.log(`  ${chalk.white(summary.summary)}`);
      console.log("");

      if (summary.keyDecisions.length > 0) {
        console.log(chalk.bold("  Key Decisions"));
        for (const d of summary.keyDecisions) {
          console.log(`    ${chalk.green("▸")} ${d}`);
        }
        console.log("");
      }

      if (summary.whatWentWell.length > 0) {
        console.log(chalk.bold("  What Went Well"));
        for (const w of summary.whatWentWell) {
          console.log(`    ${chalk.green("+")} ${w}`);
        }
        console.log("");
      }

      if (summary.whatCouldImprove.length > 0) {
        console.log(chalk.bold("  Could Improve"));
        for (const c of summary.whatCouldImprove) {
          console.log(`    ${chalk.yellow("~")} ${c}`);
        }
        console.log("");
      }

      if (summary.technicalHighlights.length > 0) {
        console.log(chalk.bold("  Technical Highlights"));
        for (const t of summary.technicalHighlights) {
          console.log(`    ${chalk.cyan("*")} ${t}`);
        }
        console.log("");
      }

      console.log(`  ${chalk.dim("Files:")} ${summary.filesImpact}`);
      console.log(`  ${chalk.dim("Cost:")} ${summary.costAssessment}`);
      console.log("");
    } catch (err) {
      spinner.fail("Failed to generate summary");
      const error = err as Error;
      console.log(chalk.red(`  ${error.message}`));
      console.log("");
    }
  } finally {
    closeDb();
  }
}

function formatMarkdown(summary: ReturnType<typeof generateAISummary> extends Promise<infer T> ? T : never): string {
  const lines: string[] = [];
  lines.push("# AI Session Summary");
  lines.push("");
  lines.push(summary.summary);
  lines.push("");

  if (summary.keyDecisions.length > 0) {
    lines.push("## Key Decisions");
    for (const d of summary.keyDecisions) lines.push(`- ${d}`);
    lines.push("");
  }

  if (summary.whatWentWell.length > 0) {
    lines.push("## What Went Well");
    for (const w of summary.whatWentWell) lines.push(`- ${w}`);
    lines.push("");
  }

  if (summary.whatCouldImprove.length > 0) {
    lines.push("## Could Improve");
    for (const c of summary.whatCouldImprove) lines.push(`- ${c}`);
    lines.push("");
  }

  if (summary.technicalHighlights.length > 0) {
    lines.push("## Technical Highlights");
    for (const t of summary.technicalHighlights) lines.push(`- ${t}`);
    lines.push("");
  }

  lines.push(`**Files:** ${summary.filesImpact}`);
  lines.push("");
  lines.push(`**Cost:** ${summary.costAssessment}`);
  lines.push("");
  lines.push("---");
  lines.push("*Generated by [Rasad](https://github.com/shami-ah/rasad) AI Summary*");

  return lines.join("\n");
}
