import chalk from "chalk";
import { getDb, closeDb } from "../../db/connection.js";
import { generateWrapped } from "../../analysis/wrapped.js";

export async function runWrapped(opts: { monthly?: boolean; json?: boolean }): Promise<void> {
  const db = getDb();
  try {
    const type = opts.monthly ? "monthly" : "weekly";
    const data = generateWrapped(db, type);

    if (opts.json) {
      console.log(JSON.stringify(data, null, 2));
      return;
    }

    const divider = chalk.dim("  " + "─".repeat(48));

    console.log("");
    console.log(chalk.bold(`  🔭 Rasad Wrapped — ${data.period}`));
    console.log(divider);
    console.log("");

    // Core stats in a card layout
    console.log(`  ${chalk.cyan.bold(data.sessions.toLocaleString())} sessions   ${chalk.cyan.bold(data.messages.toLocaleString())} messages   ${chalk.yellow.bold("$" + data.totalCost.toFixed(0))} spent`);
    console.log("");

    console.log(`  ${chalk.bold("🔧")} ${chalk.cyan(data.toolCalls.toLocaleString())} tool calls across ${chalk.green(data.filesChanged.toLocaleString())} files changed`);
    console.log("");
    console.log(divider);

    // Top model
    console.log("");
    console.log(`  ${chalk.bold("Favorite Model")}         ${chalk.white(data.topModel.name.replace("claude-", ""))}`);
    console.log(`                          ${chalk.dim(data.topModel.sessions + " sessions, $" + data.topModel.cost.toFixed(0))}`);

    // Top project
    console.log(`  ${chalk.bold("Most Active Project")}    ${chalk.white(data.topProject.name.split("/").pop())}`);
    console.log(`                          ${chalk.dim(data.topProject.sessions + " sessions, $" + data.topProject.cost.toFixed(0))}`);

    // Top tool
    console.log(`  ${chalk.bold("Most Used Tool")}         ${chalk.white(data.topTool.name)}`);
    console.log(`                          ${chalk.dim(data.topTool.count + " calls")}`);
    console.log("");
    console.log(divider);

    // Best & worst sessions
    if (data.mostExpensiveSession.id !== "none") {
      console.log("");
      console.log(`  ${chalk.bold("💸 Most Expensive")}      ${chalk.yellow("$" + data.mostExpensiveSession.cost.toFixed(2))} on ${data.mostExpensiveSession.project.split("/").pop()}`);
      console.log(`                          ${chalk.dim(data.mostExpensiveSession.messages + " messages — " + data.mostExpensiveSession.id.slice(0, 8))}`);
    }

    if (data.mostProductiveSession.id !== "none") {
      console.log(`  ${chalk.bold("⚡ Most Productive")}     ${chalk.green(data.mostProductiveSession.filesChanged + " files")} for ${chalk.yellow("$" + data.mostProductiveSession.cost.toFixed(2))} on ${data.mostProductiveSession.project.split("/").pop()}`);
      console.log(`                          ${chalk.dim(data.mostProductiveSession.id.slice(0, 8))}`);
    }
    console.log("");
    console.log(divider);

    // Daily pattern
    if (data.dailyPattern.length > 0) {
      console.log("");
      console.log(chalk.bold("  Activity by Day"));
      console.log("");
      const maxSessions = Math.max(...data.dailyPattern.map((d) => d.sessions));
      for (const d of data.dailyPattern) {
        const barLen = Math.round((d.sessions / maxSessions) * 20);
        const bar = chalk.blue("█".repeat(barLen)) + chalk.dim("░".repeat(20 - barLen));
        console.log(`    ${d.day}  ${bar}  ${d.sessions}`);
      }
    }

    // Fun facts
    if (data.funFacts.length > 0) {
      console.log("");
      console.log(divider);
      console.log("");
      console.log(chalk.bold("  Fun Facts"));
      for (const fact of data.funFacts) {
        console.log(`    ${chalk.dim("•")} ${fact}`);
      }
    }

    console.log("");
    console.log(divider);
    console.log(chalk.dim("  Generated by Rasad — AI Observatory"));
    console.log(chalk.dim("  rasad dashboard → see the full web view"));
    console.log("");
  } finally {
    closeDb();
  }
}
