import { describe, it, expect } from "vitest";
import Database from "better-sqlite3";
import { SCHEMA_SQL } from "../../db/schema.js";
import { exportPassportMarkdown, exportVibeDiffMarkdown } from "../export.js";

function createTestDb(): Database.Database {
  const db = new Database(":memory:");
  db.exec(SCHEMA_SQL);

  // Insert test session
  db.prepare(`
    INSERT INTO sessions (id, source, project, cwd, model, started_at, ended_at,
      message_count, total_input_tokens, total_output_tokens,
      total_cache_creation_tokens, total_cache_read_tokens,
      estimated_cost_usd, file_path, file_mtime, file_size)
    VALUES ('test-123', 'claude-code', '/Users/test/myproject', '/Users/test/myproject',
      'claude-opus-4-6', '2026-04-19T10:00:00Z', '2026-04-19T11:00:00Z',
      4, 10000, 5000, 0, 8000, 1.50, '/test/path.jsonl', 1000, 500)
  `).run();

  // Insert test messages
  db.prepare(`INSERT INTO messages (session_id, uuid, role, content_text, content_json, model, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, timestamp, is_sidechain, has_thinking)
    VALUES ('test-123', 'msg-1', 'user', 'Fix the auth bug', '[]', NULL, 0, 0, 0, 0, '2026-04-19T10:00:00Z', 0, 0)`).run();
  db.prepare(`INSERT INTO messages (session_id, uuid, role, content_text, content_json, model, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, timestamp, is_sidechain, has_thinking)
    VALUES ('test-123', 'msg-2', 'assistant', 'I will fix the auth bug by updating the middleware', '[]', 'claude-opus-4-6', 5000, 2500, 0, 4000, '2026-04-19T10:01:00Z', 0, 0)`).run();
  db.prepare(`INSERT INTO messages (session_id, uuid, role, content_text, content_json, model, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, timestamp, is_sidechain, has_thinking)
    VALUES ('test-123', 'msg-3', 'user', 'yes looks good', '[]', NULL, 0, 0, 0, 0, '2026-04-19T10:02:00Z', 0, 0)`).run();
  db.prepare(`INSERT INTO messages (session_id, uuid, role, content_text, content_json, model, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, timestamp, is_sidechain, has_thinking)
    VALUES ('test-123', 'msg-4', 'assistant', 'Done, the auth middleware is updated', '[]', 'claude-opus-4-6', 5000, 2500, 0, 4000, '2026-04-19T10:03:00Z', 0, 0)`).run();

  // Insert tool uses
  db.prepare(`INSERT INTO tool_uses (session_id, message_uuid, tool_name, tool_use_id, input_json, timestamp)
    VALUES ('test-123', 'msg-2', 'Edit', 'tu-1', '{"file_path":"/src/auth.ts"}', '2026-04-19T10:01:00Z')`).run();

  // Insert files touched
  db.prepare(`INSERT INTO files_touched (session_id, file_path, action, timestamp)
    VALUES ('test-123', '/src/auth.ts', 'edit', '2026-04-19T10:01:00Z')`).run();

  return db;
}

describe("exportPassportMarkdown", () => {
  it("generates markdown with all sections", () => {
    const db = createTestDb();
    const md = exportPassportMarkdown(db, "test-123");

    expect(md).not.toBeNull();
    expect(md).toContain("# Session Passport");
    expect(md).toContain("myproject");
    expect(md).toContain("opus-4-6");
    expect(md).toContain("$1.50");
    expect(md).toContain("## Tools Used");
    expect(md).toContain("Edit");
    expect(md).toContain("## Files Touched");
    expect(md).toContain("auth.ts");
    expect(md).toContain("Generated by");
    db.close();
  });

  it("returns null for non-existent session", () => {
    const db = createTestDb();
    expect(exportPassportMarkdown(db, "nonexistent")).toBeNull();
    db.close();
  });
});

describe("exportVibeDiffMarkdown", () => {
  it("generates markdown with overview", () => {
    const db = createTestDb();
    const md = exportVibeDiffMarkdown(db, "test-123");

    expect(md).not.toBeNull();
    expect(md).toContain("# Vibe Diff");
    expect(md).toContain("myproject");
    expect(md).toContain("## Overview");
    expect(md).toContain("## Conversation");
    expect(md).toContain("Fix the auth bug");
    db.close();
  });
});
